update

diff --git a/unisuite-package/DEBIAN/postinst b/unisuite-package/DEBIAN/postinst
--- a/unisuite-package/DEBIAN/postinst
+++ b/unisuite-package/DEBIAN/postinst
@@ -23,6 +23,7 @@ if ! dpkg -l | grep -q nginx; then
   exit 1
 else
   echo "Nginx ist bereits installiert."
+  systemctl enable nginx
 fi
 
 # Überprüfe ob Apache2 installiert ist
@@ -31,6 +32,7 @@ if ! dpkg -l | grep -q apache2; then
   exit 1
 else
   echo "Apache2 ist bereits installiert."
+  systemctl enable apache2
 fi
 
 # Überprüfe ob UFW installiert ist
@@ -41,6 +43,38 @@ else
   echo "UFW ist bereits installiert."
 fi
 
+# Überprüfe ob unattended-upgrades installiert ist
+if ! dpkg -l | grep -q unattended-upgrades; then
+  echo "unattended-upgrades ist nicht installiert"
+  exit 1
+else
+  echo "vunattended-upgrades ist bereits installiert."
+fi
+
+# Überprüfe ob Fail2Ban installiert ist
+if ! dpkg -l | grep -q fail2ban; then
+  echo "Fail2Ban ist nicht installiert"
+  exit 1
+else
+  echo "Fail2Ban ist bereits installiert."
+fi
+
+# Überprüfe ob ClamAV installiert ist
+if ! dpkg -l | grep -q clamav; then
+  echo "ClamAV ist nicht installiert"
+  exit 1
+else
+  echo "ClamAV ist bereits installiert."
+fi
+
+# Überprüfe ob ClamAV-Daemon installiert ist
+if ! dpkg -l | grep -q clamav-daemon; then
+  echo "ClamAV-Daemon ist nicht installiert"
+  exit 1
+else
+  echo "ClamAV-Daemon ist bereits installiert."
+fi
+
 # Überprüfe ob Certbot installiert ist
 if ! dpkg -l | grep -q certbot; then
   echo "CertBot ist nicht installiert"
@@ -48,6 +82,9 @@ if ! dpkg -l | grep -q certbot; then
 else
   echo "CertBot ist bereits installiert."
 fi
+
+# Entfernen alter Daten
+crontab -r
 
 # Permissions
 chown -R www-data:www-data /var/www/unisuite
@@ -104,6 +141,7 @@ certbot certonly --webroot -w /var/www/unisuite/docs -d "docs.unisuite.de" --non
 certbot certonly --webroot -w /var/www/unisuite/help -d "help.unisuite.de" --non-interactive --agree-tos --email lukaspoggemann@gmail.com
 certbot certonly --webroot -w /var/www/unisuite/jobs -d "jobs.unisuite.de" --non-interactive --agree-tos --email lukaspoggemann@gmail.com
 certbot certonly --webroot -w /var/www/unisuite/status -d "status.unisuite.de" --non-interactive --agree-tos --email lukaspoggemann@gmail.com
+echo "0 3 * * * /usr/bin/certbot renew --quiet --post-hook 'systemctl reload nginx'" | crontab -
 
 # NGINX neu starten
 if systemctl is-active --quiet nginx; then
@@ -128,13 +166,53 @@ systemctl daemon-reload
 systemctl enable unisuite-api.service
 systemctl start unisuite-api.service
 
+# Fail2Ban
+systemctl enable fail2ban
+systemctl start fail2ban
+
 # UFW
 echo "Konfiguriere Firewall..."
 ufw --force enable
+ufw default deny incoming
+ufw default allow outgoing
 ufw allow 80/tcp
 ufw allow 443/tcp
 ufw allow 1505/tcp
 ufw allow 22/tcp
 ufw allow 21/tcp
+ufw logging on
+
+# ClamAV
+echo "Konfiguriere Anti Virus..."
+(crontab -l; echo "0 3 * * * /usr/bin/freshclam --quiet") | crontab -
+(crontab -l; echo "30 4 * * * /usr/bin/clamscan -r /etc /var /home /usr/local /tmp -i --log=/var/log/clamav/scan.log") | crontab -
+systemctl enable clamav-daemon
+systemctl start clamav-daemon
+
+
+# Unattended Upgrades
+echo "Konfiguriere Automatische Updates..."
+systemctl enable unattended-upgrades
+systemctl start unattended-upgrades
+(crontab -l; echo "0 3 * * * /usr/bin/unattended-upgrades -d") | crontab -
 
 echo "Pre-Installation abgeschlossen."
+echo "---"
+
+# Countdown von 10 Sekunden
+echo "Das System wird neu gestartet um die Änderungen anzuwenden."
+echo "Drücken Sie Strg+C, um den Neustart abzubrechen."
+for i in {15..1}
+do
+    if [ $i -eq 1 ]; then
+        echo -ne "-> $i Sekunde verbleibt...\r"  # Einzahl
+    else
+        echo -ne "-> $i Sekunden verbleiben...\r"  # Mehrzahl
+    fi
+    sleep 1
+done
+
+# Sicherer Neustart des Systems
+echo "Das System wird jetzt neu gestartet..."
+
+shutdown -r now
